CFLAGS = -Wall -std=c11
LDLIBS = -lm

all : el_1_zad4 tankowanie zad1 zad2 zad3 zad4 zad5 zad6 zad7 zad8 zad9 zad10 zad11

clean :
	rm -f el_1_zad4 tankowanie zad1 zad2 zad3 zad4 zad5 zad6 zad7 zad8 zad9 zad10 zad11